# Generated by Django 5.2.4 on 2025-08-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
