# Generated by Django 5.2.4 on 2025-08-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_journal_personalbest_scheduledworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbest',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility & Endurance'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
