# Generated by Django 5.2.4 on 2025-08-21 00:18

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aicoachquestion_progressphoto_resttimer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicoachquestion',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='aicoachquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='progressphoto',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='resttimer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resttimer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scheduledworkout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduledworkout',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aicoachquestion',
            name='is_answered',
            field=models.BooleanField(default=False, help_text='Whether this question has been answered by the AI coach'),
        ),
        migrations.AlterField(
            model_name='aicoachquestion',
            name='answer',
            field=models.TextField(blank=True, help_text='AI-generated response to your question', null=True),
        ),
        migrations.AlterField(
            model_name='aicoachquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this question was answered', null=True),
        ),
        migrations.AlterField(
            model_name='aicoachquestion',
            name='question',
            field=models.TextField(help_text='Your question for the AI fitness coach'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(help_text='Main content of your journal entry - thoughts, progress, goals, etc.'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=home.models.get_today, help_text='Date this journal entry refers to'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(help_text='Brief title describing the journal entry', max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility & Endurance'), ('other', 'Other')], default='other', help_text='Category classification for this exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='date_achieved',
            field=models.DateField(default=home.models.get_today, help_text='Date when this personal best was achieved'),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='exercise',
            field=models.CharField(help_text='Name of the exercise or activity', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Flag to mark if this is the current personal record'),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the achievement or conditions'),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='unit',
            field=models.CharField(help_text='Unit of measurement (kg, lbs, seconds, minutes, km, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='The achieved value (weight, time, distance, etc.)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=home.models.get_today, help_text='Used for age-based fitness calculations and recommendations', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workout_info',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='Stores workout logs and exercise data in flexible JSON format'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='date',
            field=models.DateField(default=home.models.get_today, help_text='Date when this photo was taken'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='image',
            field=models.ImageField(help_text='Upload your progress photo', upload_to='progress_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about your progress or this photo'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your weight in kilograms when this photo was taken', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='date',
            field=models.DateField(help_text='Date when this workout is planned to be performed'),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of exercises and workout plan'),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the workout session'),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', help_text='Current status of the scheduled workout', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='title',
            field=models.CharField(help_text='Name or title of the workout session', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=home.models.get_today, help_text='Date when this weight measurement was taken'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms (e.g., 75.50)', max_digits=5),
        ),
        migrations.RemoveField(
            model_name='progressphoto',
            name='created_at',
        ),
    ]
