# Generated by Django 5.2.4 on 2025-08-21 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aicoachquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicoachquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this question was created'),
        ),
    ]
